### PR TITLE
More docs improvements.

### PR DESCRIPTION
**Pull request by luckydonald**

### CODE REVIEW

**Review by giuseppeM99 — CHANGES_REQUESTED** [review]
Use API Methods instead of API Commands to stay in line with the official documentation.
Also change `max-batch-operations` to `--max-batch-operations` to match the edits on the other executable parameters

**Review by giuseppeM99 — APPROVED** [review]

**Comment by giuseppeM99** [comment]
LGFM

**Review by MarcoBuster — CHANGES_REQUESTED** [review]
Thank you. Every new command line parameter has a environment variable (like `--insecure` has `TELEGRAM_INSECURE`), you can find the complete list [here](https://github.com/tdlight-team/tdlight-telegram-bot-api/blob/100a7cc8469131b595c14d6c629d573a7d4a6791/docker-entrypoint.sh#L19). It would be nice to document them all in a way you can immediately catch what environment variable is associated to a command line paramater, because most of us use Docker.

**Comment by luckydonald** [comment]
@MarcoBuster, yes we should do that in the future.
For now this should clean up what's there, mostly.

**Comment by MarcoBuster** [comment]
> @MarcoBuster, yes we should do that in the future.
> For now this should clean up what's there, mostly.

Ok. #14 contains some ideas about the future of documentation for this project.

**Review by MarcoBuster — APPROVED** [review]

**Pull request merged**
