### PR TITLE
Fix camelCase of userLogin in the docs.

### PR DESCRIPTION
**Pull request by luckydonald**

### CODE REVIEW

**Comment by code1mountain** [comment]
@luckydonald No, only userlogin in lowercase works. The case is usually ignored, but this is a special method where this is not possible. Please have a look at the respective code.

**Comment by luckydonald** [comment]
In that case it should be changed in the code to be camelCase. It really doesn't make sense to have a single endpoint work differently to all the others.

**Comment by code1mountain** [comment]
It's a bit of a mixture between an endpoint and the `/bot` or `/user` path part. I think having it lowercase is fine

**Comment by luckydonald** [comment]
@code1mountain 
If it would be `/user/login` I'd be all on board with you.
Most users would expect it to be like the telegram docs do it, camelCase.
The ability for lower case has not been documented, and are not widely known or used.

**Comment by skrtdev** [comment]
@luckydonald In the official docs of bot api is stated that all the methods names are case insensitive

**Comment by luckydonald** [comment]
@skrtdev Ah yes. Indeed. Missed that. Still, I'd rather keep it similar to the documentation's casing.

**Comment by andrew-ld** [comment]
@giuseppeM99 merge?

**Comment by MarcoBuster** [comment]
@andrew-ld the build failed (because GitHub), I just restarted it. Wait until it's completed.

**Pull request merged**
